version: '3.1'
services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env
      - .env.local
#  symfony:
#    build:
#      context: .
#      dockerfile: ./Dockerfile
#    ports:
#      - 80:80
#      - 443:443